### ISSUE TITLE
E154: Duplicate tag "vim-fetch" in file .../vim-fetch/doc/vim-fetch.txt

### ISSUE THREAD

**Issue by mgedmin** [wsdjeg/vim-fetch#1]
If I add `Plugin "kopische/vim-fetch` to my .vimrc, source it, and run `:PluginInstall`, it reports an error while running helptags.

If I run `:helptags ~/.vim/bundle/kopische/vim-fetch/`, I get

```
E154: Duplicate tag "vim-fetch" in file /home/mg/.vim/bundle/vim-fetch/doc/vim-fetch.txt
E154: Duplicate tag "vim-fetch" in file /home/mg/.vim/bundle/vim-fetch/doc/vim-fetch.txt
E154: Duplicate tag "vim-fetch" in file /home/mg/.vim/bundle/vim-fetch/doc/vim-fetch.txt
E154: Duplicate tag "vim-fetch" in file /home/mg/.vim/bundle/vim-fetch/doc/vim-fetch.txt
```

**Comment by kopischke** [comment]
Yeah, my bad: I had a brainfart and tried to use Markdown italics. Will fix ASAP.

**Comment by kopischke** [comment]
@mgedmin fixed in latest release. Thanks for reporting!

**Comment by mgedmin** [comment]
Thank you for the very quick fix!
